# Generated by Django for VolunteerProfile photo, aadhar fields
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('donations', '0003_alter_restaurantprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='profile_photo',
            field=models.ImageField(upload_to='volunteer_photos/', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='aadhar_card',
            field=models.CharField(max_length=12, unique=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='aadhar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
