# Generated by Django 6.0.1 on 2026-02-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_ngofoodrequest'),
        ('donations', '0004_volunteerprofile_photo_aadhar'),
    ]

    operations = [
    ]
