# Generated by Django 6.0.1 on 2026-02-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_merge_20260203_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngofoodrequest',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='ngofoodrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_ngo_requests', to='donations.restaurantprofile'),
        ),
        migrations.AlterField(
            model_name='ngofoodrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
