# Generated by Django 6.0.1 on 2026-02-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_ngofoodrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuptask',
            name='ngo_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.ngofoodrequest'),
        ),
        migrations.AlterField(
            model_name='pickuptask',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.surplusfoodrequest'),
        ),
    ]
