# Generated by Django 6.0.1 on 2026-05-16 18:57

import django.core.validators
import django.db.models.deletion
import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_dynamic_notification_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=donations.models.ngo_gallery_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), donations.models.validate_gallery_image_size])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='donations.ngoprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ngo', '-created_at'], name='donations_n_ngo_id_9fd543_idx')],
            },
        ),
    ]
