# Generated by Django 6.0.1 on 2026-05-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_ngogalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTrustFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('suspicious', 'Suspicious')], default='accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='flag_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pickuptask',
            index=models.Index(fields=['status', 'assigned_at'], name='donations_p_status_170486_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuptask',
            index=models.Index(fields=['assigned_to', 'status'], name='donations_p_assigne_650178_idx'),
        ),
        migrations.AddField(
            model_name='volunteertrustflag',
            name='pickup_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_flag', to='donations.pickuptask'),
        ),
        migrations.AddField(
            model_name='volunteertrustflag',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_flags', to='donations.volunteerprofile'),
        ),
        migrations.AddIndex(
            model_name='volunteertrustflag',
            index=models.Index(fields=['volunteer', 'flagged_at'], name='donations_v_volunte_7ac0b7_idx'),
        ),
    ]
