# Generated by Django 6.0.1 on 2026-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_volunteertrustflag_pickuptask_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
