# Generated by Django 6.0.1 on 2026-05-16 20:05

import django.core.validators
import django.db.models.deletion
import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_volunteerprofile_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuptask',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='delivery_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to=donations.models.volunteer_delivery_proof_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), donations.models.validate_gallery_image_size]),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='ngo_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='failed_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='ngo_confirmations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='successful_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='suspicious_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='VolunteerTrustScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_change', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_score_logs', to='donations.pickuptask')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_logs', to='donations.volunteerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['volunteer', 'created_at'], name='donations_v_volunte_1a69bf_idx')],
            },
        ),
    ]
