# Generated by Django 6.0.1 on 2026-05-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_pickuptask_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngogalleryimage',
            name='pickup_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_proof_images', to='donations.pickuptask'),
        ),
        migrations.AddField(
            model_name='pickuptask',
            name='transparency_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('awaiting_distribution_proof', 'Awaiting Distribution Proof'), ('proof_uploaded', 'Proof Uploaded'), ('verified', 'Verified')], default='delivered', max_length=32),
        ),
    ]
